version: '3'


services:
  bot:
    container_name: restriction-bot
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: "python -m src.main"
